const tableHeaders = [
  "Date",
  "Name",
  "Merchant Name",
  "Payment Channel",
  "ISO Currency Code",
  "Plaid Category 1",
  "Plaid Category 2",
  "Plaid Category 3",
  "Category ID",
  "Transaction Space",
  "Transaction Type",
  "Transaction ID",
  "Mask",
  "Account Name",
  "Account Type",
  "Account Subtype",
  "Address",
  "City",
  "Region",
  "Postal Code",
  "Country",
  "Store Number",
  "Category",
  "Owner",
  "Amount",
];

const plaidCategory3Map = {
  "Charities and Non-Profits": "Donations",
  "Coffee Shop": "Food and Drink",
  "Fast Food": "Food and Drink",
  Dentists: "Healthcare",
  "Maintenance and Repair": "Automotive",
  "Printing and Publishing": "Misc",
  "Banking and Finance": "Financial",
  "Loans and Mortgages": "Financial",
  "Stock Brokers": "Financial",
  Taxes: "Financial",
  "Property Management": "Misc",
  Electric: "Utilities",
  Check: "Transfer",
  "Kids' Store": "Clothing and Accessories",
  "Men's Store": "Clothing and Accessories",
  "Shoe Store": "Clothing and Accessories",
  "Women's Store": "Clothing and Accessories",
  "Beer, Wine and Spirits": "Food and Drink",
  ATM: "Transfer",
  Benefits: "Transfer",
  "Chase QuickPay": "Transfer",
  Coinbase: "Transfer",
  PayPal: "Transfer",
  Square: "Food and Drink",
  Venmo: "Transfer",
  "Ride Share": "Taxi/Ride Share",
  "Hotels and Motels": "Lodging",
};

const plaidCategory2Map = {
  Education: "Education",
  "Government Departments and Agencies": "Government Departments and Agencies",
  "Organizations and Associations": "Donations",
  "Public and Social Services": "Donations",
  Bar: "Food and Drink",
  Restaurants: "Food and Drink",
  "Healthcare Services": "Healthcare",
  "Interest Earned": "Interest Earned",
  "Credit Card": "Credit Card",
  Rent: "Rent",
  "Arts and Entertainment": "Arts and Entertainment",
  Golf: "Fitness",
  "Gyms and Fitness Centers": "Fitness",
  "Sports Clubs": "Fitness",
  "Stadiums and Arenas": "Arts and Entertainment",
  Automotive: "Automotive",
  "Business Services": "Misc",
  Cable: "Utilities",
  Entertainment: "Arts and Entertainment",
  Financial: "Financial",
  "Food and Beverage": "Food and Drink",
  Insurance: "Insurance",
  "Internet Services": "Utilities",
  "Personal Care": "Health & Wellness",
  "Real Estate": "Misc",
  "Shipping and Freight": "Misc",
  Storage: "Rent",
  Subscription: "Arts and Entertainment",
  "Telecommunication Services": "Utilities",
  "Travel Agents and Tour Operators": "Arts and Entertainment",
  Utilities: "Utilities",
  Veterinarians: "Pet",
  "Arts and Crafts": "Arts and Entertainment",
  "Beauty Products": "Health & Wellness",
  Bicycles: "Fitness",
  "Clothing and Accessories": "Clothing and Accessories",
  "Computers and Electronics": "Computers and Electronics",
  "Convenience Stores": "Groceries",
  "Department Stores": "Clothing and Accessories",
  "Digital Purchase": "Amazon",
  "Equipment Rental": "Fitness",
  Florists: "Home",
  "Food and Beverage Store": "Food and Drink",
  "Furniture and Home Decor": "Home",
  "Glasses and Optometrist": "Healthcare",
  "Hardware Store": "Home",
  "Jewelry and Watches": "Clothing and Accessories",
  "Lawn and Garden": "Home",
  "Music, Video and DVD": "Arts & Entertainment",
  Pets: "Pet",
  Pharmacies: "Personal Care",
  "Photos and Frames": "Home",
  "Sporting Goods": "Fitness",
  "Supermarkets and Groceries": "Groceries",
  Recreation: "Arts and Entertainment",
  Toys: "Misc",
  "Vintage and Thrift": "Clothing and Accessories",
  "Warehouses and Wholesale Stores": "Groceries",
  Payment: "Tax",
  Refund: "Tax",
  Credit: "Transfer",
  Debit: "Transfer",
  Deposit: "Transfer",
  "Internal Account Transfer": "Transfer",
  Payroll: "Transfer",
  "Third Party": "Transfer",
  Withdrawal: "Transfer",
  "Airlines and Aviation Services": "Big Transportation",
  Boat: "Big Transportation",
  "Car and Truck Rentals": "Car Rentals",
  "Car Service": "Ride Share",
  "Gas Stations": "Gas Stations",
  Lodging: "Lodging",
  Parking: "Parking",
  "Public Transportation Services": "Public Transportation",
  Rail: "Big Transportation",
  Taxi: "Ride Share",
};
